openapi: 3.0.3
info:
  title: Payments API
  version: 1.0.0

paths:
  /payments:
    post:
      summary: Create a new payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
      responses:
        '201':
          description: Payment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'

  /payments/{id}:
    get:
      summary: Get a payment by ID, optionally converted to another currency
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: currency
          in: query
          required: false
          schema:
            type: string
            description: currency description to convert to (e.g., Canada-Dollar)
      responses:
        '200':
          description: Payment found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404':
          description: Payment not found

components:
  schemas:
    CreatePaymentRequest:
      type: object
      required:
        - description
        - transactionDate
        - purchaseAmount
      properties:
        description:
          type: string
        transactionDate:
          type: integer
          description: Unix timestamp in milliseconds
        purchaseAmount:
          type: number
          format: double
          description: Dollar amount of purchase

    PaymentResponse:
      type: object
      required:
        - id
        - description
        - transactionDate
        - purchaseAmount
        - currency
      properties:
        description:
          type: string
        transactionDate:
          type: integer
          description: Unix timestamp in milliseconds
        purchaseAmount:
          type: number
          format: double
        currency:
          type: string
